"""Offline Markdown draft. Used with --raw, or when no AI CLI is available."""

from __future__ import annotations

import re
from typing import Dict, List, Tuple

from .models import Commit, Session
from .summarize import Project, Report

_CC = re.compile(r"^(\w+)(?:\(([^)]*)\))?!?:\s*(.+)$")

T: Dict[str, Dict[str, str]] = {
    "zh": {
        "daily": "工作日报", "weekly": "工作周报", "custom": "工作小结",
        "summary": "一句话总结", "done": "今日完成", "done_w": "本周重点成果",
        "risk": "问题与风险", "plan": "明日计划", "plan_w": "下周计划",
        "stats": "数据看板", "overview": "本周节奏",
        "risk_hint": "_有没有卡点？按「现象 → 影响 → 方案 → 需要谁在何时前给什么支持」写；没有就写“无”。_",
        "plan_hint": "_写 1–3 件，每件带交付物和时间节点。_",
        "footer": "由 report-skill 根据本地 Agent 对话与 git 历史生成，投入时长为估算值，发出前请人工复核。",
        "project": "项目", "commits": "提交", "lines": "代码行", "sessions": "AI 会话", "files": "改动文件",
        "time": "投入", "more_commits": "等 {n} 次提交", "more_sessions": "另有 {n} 个会话",
        "turns": "{n} 轮", "meetings": "会议", "lark_tasks": "飞书任务", "due": "截止",
        "meeting_part": "参加 {n} 场会议（约 {h}）", "task_part": "完成 {n} 项飞书任务", "more_meetings": "另有 {n} 场", "nothing": "这段时间没有找到任何 Agent 对话、git 提交或飞书记录。",
        "top_part": "{when}主要投入在 {top}", "hours_part": "有效投入约 {hours}", "sep": "，", "end": "。", "lead": "{when}",
        "today": "今天", "this_week": "本周", "this_period": "这段时间",
        "commit_part": "提交 {n} 次代码（+{ins}/−{dels}）", "session_part": "与 AI Agent 协作 {n} 个会话",
        "hours": "{h} 小时", "and": "、",
        "weekdays": "周一 周二 周三 周四 周五 周六 周日",
    },
    "en": {
        "daily": "Daily Report", "weekly": "Weekly Report", "custom": "Work Summary",
        "summary": "TL;DR", "done": "Done today", "done_w": "Key results this week",
        "risk": "Risks & blockers", "plan": "Plan for tomorrow", "plan_w": "Plan for next week",
        "stats": "Numbers", "overview": "Week at a glance",
        "risk_hint": "_Anything blocked? Write symptom → impact → options → what you need from whom by when. Or “None”._",
        "plan_hint": "_1–3 items, each with a deliverable and a deadline._",
        "footer": "Generated by report-skill from local agent sessions and git history. Time is an estimate; review before sending.",
        "project": "Project", "commits": "Commits", "lines": "Lines", "sessions": "AI sessions", "files": "Files",
        "time": "Time", "more_commits": "and {n} more commits", "more_sessions": "{n} more sessions",
        "turns": "{n} turn{s}", "meetings": "Meetings", "lark_tasks": "Lark tasks", "due": "due",
        "meeting_part": "{n} meeting{s} (~{h})", "task_part": "{n} Lark task{s} done", "more_meetings": "{n} more", "nothing": "No agent sessions, git commits or Lark activity found in this period.",
        "top_part": "{when} went mostly into {top}", "hours_part": "about {hours} of focused work", "sep": "; ", "end": ".", "lead": "{when}",
        "today": "Today", "this_week": "This week", "this_period": "This period",
        "commit_part": "{n} commit{s} (+{ins}/−{dels})", "session_part": "{n} AI-agent session{s}",
        "hours": "{h}h", "and": ", ",
        "weekdays": "Mon Tue Wed Thu Fri Sat Sun",
    },
}

CC_LABELS = {
    "zh": {"feat": "新增", "fix": "修复", "refactor": "重构", "perf": "优化", "docs": "文档", "test": "测试",
           "chore": "维护", "ci": "CI", "build": "构建", "style": "样式", "revert": "回滚"},
    "en": {"feat": "Added", "fix": "Fixed", "refactor": "Refactored", "perf": "Sped up", "docs": "Docs",
           "test": "Tests", "chore": "Chore", "ci": "CI", "build": "Build", "style": "Style", "revert": "Reverted"},
}


def _pl(n: int) -> str:
    return "" if n == 1 else "s"


def hours(minutes: int, lang: str) -> str:
    h = minutes / 60
    text = f"{h:.1f}".rstrip("0").rstrip(".") if h < 10 else f"{h:.0f}"
    return T[lang]["hours"].format(h=text)


def commit_line(c: Commit, lang: str) -> str:
    m = _CC.match(c.subject)
    if m and m.group(1).lower() in CC_LABELS[lang]:
        label = CC_LABELS[lang][m.group(1).lower()]
        scope = f"[{m.group(2)}] " if m.group(2) else ""
        text = f"{label}：{scope}{m.group(3)}" if lang == "zh" else f"{label}: {scope}{m.group(3)}"
    else:
        text = c.subject
    return f"{text} (`{c.sha[:7]}`)"


def session_label(s: Session, limit: int = 60) -> str:
    label = s.title.strip() if s.title else ""
    if not label and s.prompts:
        label = s.prompts[0][1]
    label = re.sub(r"\s+", " ", label)
    return label if len(label) <= limit else label[: limit - 1] + "…"


SOURCE_NAMES = {"claude-code": "Claude Code", "codex": "Codex", "zcode": "ZCode"}


def project_bullets(p: Project, lang: str, max_commits: int = 6, max_sessions: int = 4) -> List[str]:
    t = T[lang]
    lines: List[str] = []
    commits = sorted(p.commits, key=lambda c: c.insertions + c.deletions, reverse=True)
    for c in sorted(commits[:max_commits], key=lambda c: c.time):
        lines.append(commit_line(c, lang))
    if len(commits) > max_commits:
        lines.append(t["more_commits"].format(n=len(commits) - max_commits))
    sessions = sorted(p.sessions, key=lambda s: len(s.prompts), reverse=True)
    seen = set()
    shown = 0
    for s in sessions:
        label = session_label(s)
        if not label or label in seen:
            continue
        seen.add(label)
        if shown >= max_sessions:
            continue
        shown += 1
        meta = SOURCE_NAMES.get(s.source, s.source)
        if s.prompts:
            meta += " · " + t["turns"].format(n=len(s.prompts), s=_pl(len(s.prompts)))
        lines.append(f"{label} _({meta})_")
    if len(seen) > shown:
        lines.append(t["more_sessions"].format(n=len(seen) - shown))
    return lines


def summary_line(r: Report, lang: str) -> str:
    """One sentence built only from the parts that actually have data."""
    t = T[lang]
    when = {"daily": t["today"], "weekly": t["this_week"]}.get(r.period.kind, t["this_period"])
    top = t["and"].join(f"**{p.name}**" for p in r.projects[:3])
    parts = [t["top_part"].format(when=when, top=top)] if top else []
    commits = r.commits
    if commits:
        parts.append(t["commit_part"].format(n=len(commits), s=_pl(len(commits)),
                                             ins=sum(c.insertions for c in commits),
                                             dels=sum(c.deletions for c in commits)))
    if r.sessions:
        parts.append(t["session_part"].format(n=len(r.sessions), s=_pl(len(r.sessions))))
    if r.lark.meetings:
        n = len(r.lark.meetings)
        parts.append(t["meeting_part"].format(n=n, s=_pl(n), h=hours(r.lark.meeting_minutes, lang)))
    if r.lark.tasks_done:
        n = len(r.lark.tasks_done)
        parts.append(t["task_part"].format(n=n, s=_pl(n)))
    if r.minutes:
        parts.append(t["hours_part"].format(hours=hours(r.minutes, lang)))
    if not top and parts:
        parts[0] = t["lead"].format(when=when) + ("" if lang == "zh" else ": ") + parts[0]
    return t["sep"].join(parts) + t["end"]


def title(r: Report, lang: str) -> str:
    t = T[lang]
    per = r.period
    wd = t["weekdays"].split()
    if per.kind == "daily":
        return f"{t['daily']} · {per.first_day.isoformat()} {wd[per.first_day.weekday()]}"
    return f"{t[per.kind]} · {per.first_day.isoformat()} ~ {per.last_day.isoformat()}"


def stats_table(r: Report, lang: str) -> List[str]:
    t = T[lang]
    rows = [f"| {t['project']} | {t['commits']} | {t['lines']} | {t['sessions']} | {t['files']} | {t['time']} |",
            "| --- | ---: | ---: | ---: | ---: | ---: |"]
    for p in r.projects:
        lines = f"+{p.insertions}/−{p.deletions}" if p.commits else "–"
        rows.append(f"| {p.name} | {len(p.commits) or '–'} | {lines} | {len(p.sessions) or '–'} | "
                    f"{len(p.files) or '–'} | {hours(p.minutes, lang)} |")
    return rows


def week_bars(r: Report, lang: str) -> List[str]:
    wd = T[lang]["weekdays"].split()
    peak = max(r.minutes_by_day.values() or [0]) or 1
    out = ["```"]
    for d, m in r.minutes_by_day.items():
        n = round(12 * m / peak)
        out.append(f"{wd[d.weekday()]} {d.strftime('%m-%d')}  {'█' * n}{'░' * (12 - n)}  {hours(m, lang)}")
    out.append("```")
    return out


def lark_lines(r: Report, lang: str, weekly: bool) -> List[str]:
    """Meetings and completed Lark tasks, appended to the "done" section."""
    t = T[lang]
    out: List[str] = []
    act = r.lark
    if act.meetings:
        out.append(f"### {t['meetings']} · {len(act.meetings)} · {hours(act.meeting_minutes, lang)}")
        limit = 8
        for m in act.meetings[:limit]:
            when = m.start.strftime("%m-%d %H:%M" if weekly else "%H:%M")
            out.append(f"- {when} {m.summary}")
        if len(act.meetings) > limit:
            out.append(f"- {t['more_meetings'].format(n=len(act.meetings) - limit)}")
        out.append("")
    if act.tasks_done:
        out.append(f"### {t['lark_tasks']} · {len(act.tasks_done)}")
        out += [f"- ✅ {task.summary}" for task in act.tasks_done[:10]] + [""]
    return out


def plan_lines(r: Report, lang: str) -> List[str]:
    t = T[lang]
    if not r.lark.tasks_open:
        return [f"1. {t['plan_hint']}", ""]
    out = []
    for i, task in enumerate(r.lark.tasks_open[:5], 1):
        due = f"（{t['due']} {task.due_at.strftime('%m-%d')}）" if lang == "zh" and task.due_at else (
            f" ({t['due']} {task.due_at.strftime('%m-%d')})" if task.due_at else "")
        out.append(f"{i}. {task.summary}{due}")
    return out + [""]


def draft(r: Report, lang: str) -> str:
    t = T[lang]
    weekly = r.period.kind != "daily"
    out: List[str] = [f"# {title(r, lang)}", ""]
    if not r.projects and not r.lark:
        out += [t["nothing"], ""]
        return "\n".join(out)
    out += [f"**{t['summary']}**：{summary_line(r, lang)}" if lang == "zh"
            else f"**{t['summary']}**: {summary_line(r, lang)}", ""]
    if weekly:
        out += [f"## {t['overview']}", ""] + week_bars(r, lang) + [""]
    out += [f"## {t['done_w'] if weekly else t['done']}", ""]
    for i, p in enumerate(r.projects, 1):
        bullets = project_bullets(p, lang, max_commits=8 if weekly else 6, max_sessions=5 if weekly else 4)
        if not bullets:
            continue
        out.append(f"### {i}. {p.name} · {hours(p.minutes, lang)}")
        out += [f"- {b}" for b in bullets] + [""]
    out += lark_lines(r, lang, weekly)
    out += [f"## {t['risk']}", "", f"- {t['risk_hint']}", ""]
    out += [f"## {t['plan_w'] if weekly else t['plan']}", ""] + plan_lines(r, lang)
    if r.projects:
        out += [f"## {t['stats']}", ""] + stats_table(r, lang) + [""]
    out += [f"<sub>{t['footer']}</sub>", ""]
    return "\n".join(out)
